dubbo:
  protocol:
    port: 28182
  application:
    name: provider-ticket
    qos-port: 33333
    qos-enable: true
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://192.168.137.110:2181
  scan:
    base-packages: com.ityj.dubbo.service  # 可以用 @DubboComponentScan
server:
  port: 8182
