server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true
