server:
  port: 9527


# feign日志以什么级别监控哪个接口
logging:
  level:
    com:
      ityj:
        cloud:
          apis:
            PayFeignApi: debug

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                     #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service               #application  name
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #application  name
          predicates:
            - Path=/a/b/c/{segment}              # 断言，路径相匹配的进行路由
            - After=2025-08-03T07:28:21.328677+08:00[Asia/Shanghai]   # 在这个日期之后生效  Before/Between 同理
            - Cookie=myCookie,123   # 需要带着cookie   -- myCookie=123才生效
            - UserAccess=diamond
          filters:
            - AddRequestHeader=req_header_test, blue
            - AddRequestParameter=gender, male
#            - RedirectTo=302, https://www.bilibili.com/ 重定向到bilibili
            - SetResponseHeader=resp_header_test, red
            - PrefixPath=/pay
            - SetPath=/pay/gateway/{segment}
            - Username=
        - id: pay_routh3
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/getAll/**
