spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.110/mydb?serverTimezone=EST
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: spring-boot
  data:
    redis:
      host: 192.168.137.110
      port: 6379
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        yml: application/yml
#  mvc:
#    static-path-pattern: /pages/**

space:
  name: uu